import { useState } from 'react'
import { LabTabs } from '../../components/ui/LabTabs'
type Tab='coordinates'|'solids'|'polygons'|'scale'
const tabs=[{id:'coordinates',label:'Mapa cartesiano',skills:'EF05MA14–15'},{id:'solids',label:'Sólidos e planificações',skills:'EF05MA16'},{id:'polygons',label:'Detetive de polígonos',skills:'EF05MA17'},{id:'scale',label:'Ampliar e reduzir',skills:'EF05MA18'}] as const
export function GeometryLab(){const [tab,setTab]=useState<Tab>('coordinates');return <section className="lab-page"><LabTabs tabs={[...tabs]} active={tab} onChange={setTab}/>{tab==='coordinates'&&<Coordinates/>}{tab==='solids'&&<Solids/>}{tab==='polygons'&&<Polygons/>}{tab==='scale'&&<Scale/>}</section>}
function Coordinates(){const [x,setX]=useState(3);const [y,setY]=useState(2);return <article className="panel activity"><header><p className="eyebrow">Primeiro quadrante</p><h2>Mapa cartesiano</h2><p>Clique em uma célula para mover o robô.</p></header><div className="coordinate-layout"><div className="coordinate-grid">{Array.from({length:36},(_,i)=>{const cx=i%6;const cy=5-Math.floor(i/6);return <button key={i} className={cx===x&&cy===y?'active':''} onClick={()=>{setX(cx);setY(cy)}}>{cx===x&&cy===y?'🤖':''}</button>})}</div><div className="coordinate-readout"><strong>({x}, {y})</strong><p>{x} passos para a direita<br/>{y} passos para cima</p></div></div></article>}
const solids=[{name:'Cubo',emoji:'🧊',faces:6,edges:12,vertices:8,net:'▦'},{name:'Prisma triangular',emoji:'⛺',faces:5,edges:9,vertices:6,net:'▱'},{name:'Pirâmide',emoji:'🔺',faces:5,edges:8,vertices:5,net:'✣'},{name:'Cilindro',emoji:'🥫',faces:3,edges:2,vertices:0,net:'◉▭◉'}]
function Solids(){const [index,setIndex]=useState(0);const solid=solids[index];return <article className="panel activity"><header><p className="eyebrow">Figuras espaciais</p><h2>Sólidos e planificações</h2></header><div className="solid-stage"><div className="solid-shape">{solid.emoji}</div><div className="solid-net">{solid.net}</div></div><div className="solid-facts"><span>Faces<strong>{solid.faces}</strong></span><span>Arestas<strong>{solid.edges}</strong></span><span>Vértices<strong>{solid.vertices}</strong></span></div><div className="quick-values">{solids.map((item,i)=><button key={item.name} className={index===i?'active':''} onClick={()=>setIndex(i)}>{item.name}</button>)}</div></article>}
const polygonData=[['Triângulo',3],['Quadrilátero',4],['Pentágono',5],['Hexágono',6]] as const
function Polygons(){const [index,setIndex]=useState(1);const [name,sides]=polygonData[index];const points=Array.from({length:sides},(_,i)=>{const a=(i/sides)*Math.PI*2-Math.PI/2;return `${100+75*Math.cos(a)},${100+75*Math.sin(a)}`}).join(' ');return <article className="panel activity"><header><p className="eyebrow">Lados, vértices e ângulos</p><h2>Detetive de polígonos</h2></header><div className="polygon-stage"><svg viewBox="0 0 200 200" aria-label={name}><polygon points={points}/>{points.split(' ').map((point,i)=>{const [cx,cy]=point.split(',');return <circle key={i} cx={cx} cy={cy} r="5"/>})}</svg><div><h3>{name}</h3><p>{sides} lados · {sides} vértices · {sides} ângulos</p></div></div><div className="quick-values">{polygonData.map((item,i)=><button key={item[0]} className={index===i?'active':''} onClick={()=>setIndex(i)}>{item[0]}</button>)}</div></article>}
function Scale(){const [factor,setFactor]=useState(2);return <article className="panel activity"><header><p className="eyebrow">Proporcionalidade na malha</p><h2>Ampliar e reduzir</h2></header><label className="big-input">Fator <input type="range" min="1" max="3" step="0.5" value={factor} onChange={e=>setFactor(Number(e.target.value))}/><strong>{factor}×</strong></label><div className="scale-stage"><div className="grid-paper"><span className="scale-rect original">2 × 3</span></div><span>→</span><div className="grid-paper"><span className="scale-rect" style={{width:`${60*factor}px`,height:`${40*factor}px`}}>{2*factor} × {3*factor}</span></div></div><p className="teacher-tip">Os comprimentos mudam pelo mesmo fator; os ângulos permanecem congruentes.</p></article>}
