import { useState } from 'react'
import { LabTabs } from '../../components/ui/LabTabs'
type Tab='converter'|'area'|'volume'
const tabs=[{id:'converter',label:'Estação de medidas',skills:'EF05MA19'},{id:'area',label:'Área × perímetro',skills:'EF05MA20'},{id:'volume',label:'Construtor de volume',skills:'EF05MA21'}] as const
export function MeasuresLab(){const [tab,setTab]=useState<Tab>('converter');return <section className="lab-page"><LabTabs tabs={[...tabs]} active={tab} onChange={setTab}/>{tab==='converter'&&<Converter/>}{tab==='area'&&<AreaPerimeter/>}{tab==='volume'&&<Volume/>}</section>}
const conversions={comprimento:{from:'m',to:'cm',factor:100},massa:{from:'kg',to:'g',factor:1000},capacidade:{from:'L',to:'mL',factor:1000},tempo:{from:'h',to:'min',factor:60}}
function Converter(){const [kind,setKind]=useState<keyof typeof conversions>('comprimento');const [value,setValue]=useState(2.5);const unit=conversions[kind];return <article className="panel activity"><header><p className="eyebrow">Transformações entre unidades</p><h2>Estação de medidas</h2></header><div className="quick-values">{Object.keys(conversions).map(item=><button key={item} className={kind===item?'active':''} onClick={()=>setKind(item as keyof typeof conversions)}>{item}</button>)}</div><div className="converter"><label>Valor em {unit.from}<input type="number" step="0.1" value={value} onChange={e=>setValue(Number(e.target.value))}/></label><span>× {unit.factor}</span><strong>{(value*unit.factor).toLocaleString('pt-BR')} {unit.to}</strong></div></article>}
function AreaPerimeter(){const [width,setWidth]=useState(5);const [height,setHeight]=useState(3);return <article className="panel activity"><header><p className="eyebrow">Investigue relações</p><h2>Área × perímetro</h2></header><div className="dimension-controls"><label>Largura <input type="range" min="1" max="10" value={width} onChange={e=>setWidth(Number(e.target.value))}/><strong>{width}</strong></label><label>Altura <input type="range" min="1" max="8" value={height} onChange={e=>setHeight(Number(e.target.value))}/><strong>{height}</strong></label></div><div className="area-grid" style={{gridTemplateColumns:`repeat(${width},32px)`}}>{Array.from({length:width*height},(_,i)=><span key={i}/>)}</div><div className="result-pair"><span>Área<strong>{width*height} u²</strong></span><span>Perímetro<strong>{2*(width+height)} u</strong></span></div></article>}
function Volume(){const [width,setWidth]=useState(3);const [depth,setDepth]=useState(2);const [height,setHeight]=useState(2);const count=width*depth*height;return <article className="panel activity"><header><p className="eyebrow">Empilhamento de cubos</p><h2>Construtor de volume</h2></header><div className="dimension-controls">{[['Largura',width,setWidth],['Profundidade',depth,setDepth],['Altura',height,setHeight]].map(([label,value,setter])=><label key={label as string}>{label as string}<input type="range" min="1" max="5" value={value as number} onChange={e=>(setter as (n:number)=>void)(Number(e.target.value))}/><strong>{value as number}</strong></label>)}</div><div className="cube-stack">{Array.from({length:count},(_,i)=><span key={i}>◼</span>)}</div><p className="math-sentence">{width} × {depth} × {height} = {count} cubos unitários</p></article>}
